### ISSUE TITLE
Personajes dibujándose debajo de otros

### ISSUE THREAD

**Issue by xzebra** [voidpixel/game#1]
![unknown](https://user-images.githubusercontent.com/20362769/58905575-5959f080-870a-11e9-96f3-5378cfd7d5c7.png)

**Comment by Klariff** [comment]
Nombres de jugador también: 
<img width="119" alt="Screen Shot 2019-06-08 at 7 17 27 AM" src="https://user-images.githubusercontent.com/30582970/59147149-9bf72380-89bd-11e9-8203-832ee48fcced.png">
