### ISSUE TITLE
Al estar yendo a un bloque y cerrar el juego antes de llegar, el bloque se queda instransitable 

### ISSUE THREAD

**Issue by jultrun** [voidpixel/game#14]
si con mi personaje voy a un bloque y cierro o recargo el juego, cuando regreso el bloque a donde intentaba ir se queda intransitable

**Comment by jultrun** [comment]
![2019-06-04_14-44-59](https://user-images.githubusercontent.com/6674993/58921113-e9903980-86fa-11e9-9ebd-d8931df982a1.gif)

**Comment by pagoru** [comment]
Aunque esta estaba antes, duplicado de #16
