### ISSUE TITLE
Al desconectarse un usuario en movimiento, se queda un bloque intransitable.

### ISSUE THREAD

**Issue by miguelaguero96** [voidpixel/game#16]
**Describe the bug**
Cuando vas hacia cualquiera de las 4 esquinas , tienen 3 bloques cada una si intentas pisar el bloque de en medio no avanza y es imposible pisarlo.

Múltiples sesiones simultáneas generan conflictos:

- Los jugadores aparecen con coordenadas diferentes.
- ~~El desplazamiento del jugador es inconsistente para las demás sesiones.~~ (La conexión se corta pero la última acción sigue en curso)

**To Reproduce**
1. Ir a una esquina
2. Ir probando en cada uno de los 3 bloques que contiene la esquina
3. No poder pisar el bloque de en medio
4. BUG

rel: #14, #17, #20, #21

**Screenshots**

![gif](https://media.giphy.com/media/piTBv0MRQtTelPSXvw/giphy.gif)
![](https://user-images.githubusercontent.com/6674993/59150764-851cf500-89ee-11e9-9a9c-7595982839fe.gif)

**Comment by Tau5** [comment]
La única esquina no afectada es la superior derecha

**Comment by Gajef** [comment]
No solo son las esquinas; he encontrado más casillas: [Screenshot](https://www.dropbox.com/s/ti0lavj8bfy5kp3/Captura%20de%20pantalla%202019-06-08%2016.38.21.png?dl=0).
Todas las que he coloreado son intransitables.

**Comment by jultrun** [comment]
eso pasa al intentar ir a un bloque y desconectar, varios los genere yo al testear
