### ISSUE TITLE
Avisar a un cliente desconectado en multiples sesiones

### ISSUE THREAD

**Issue by Klariff** [voidpixel/game#20]
Múltiples sesiones simultáneas generan conflictos:
- Los jugadores aparecen con coordenadas diferentes.
- El desplazamiento del jugador es inconsistente para las demás sesiones.

**Comment by pagoru** [comment]
Realmente no genera ningún conflicto, solo que la primera sesión se desconecta y no se actualiza más. No es un bug, funciona como debe, aunque estaría bien notificar a la sesión desconectada.

**Comment by jultrun** [comment]
si tienes dos ventanas una a punto de iniciar sección y la otra ya iniciada y vas a un bloque y antes de llegar inicias con la otra, en la otra apareces en lugar a donde tenias que ir pero al pulsar en otro bloque te tele-trasportas al spawn vas al bloque
![2019-06-08_13-06-35](https://user-images.githubusercontent.com/6674993/59150764-851cf500-89ee-11e9-9a9c-7595982839fe.gif)

**Comment by pagoru** [comment]
🤔 Muy interesante.... deberia cancelarse la acción al desconectarte.

**Comment by pagoru** [comment]
Esta relacionada con la #16, cierro esta y traslado información.
