### ISSUE TITLE
Mapa mal renderizado en los bordes [BUG]

### ISSUE THREAD

**Issue by chispaLBC** [voidpixel/game#26]
**Describe the bug**
Se renderiza mal el mapa segun el zoom de la pestaña y dependiendo de si la ventana está maximizada.

**To Reproduce**
1. Entrar al juego

**Expected behavior**
No deberia haber esos pinchos

**Screenshots**
![image](https://user-images.githubusercontent.com/42807484/59163140-0793da80-8afd-11e9-91e7-a65ecc104efb.png)
![image](https://user-images.githubusercontent.com/42807484/59163165-7bce7e00-8afd-11e9-80f5-d403e120ba67.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 75.0.3770.80 (Build oficial) (64 bits)
- Grafica nvidia 1070 gigabyte g1
- Procesador ryzen 5 1600
- Monitor Acer GN246HLB

**Comment by pagoru** [comment]
¿Qué monitor estás usando?

**Comment by chispaLBC** [comment]
Acer GN246HLB

**Comment by pagoru** [comment]
¿Puedes poner en la consola de tu navegador esto y decirme el número?
```js
window.devicePixelRatio
```
Seguramente sea **1**, pero quiero asegurarme.

**Comment by chispaLBC** [comment]
Sí, es 1

**Comment by pagoru** [comment]
Vale, tengo localizado el problema.
En cuanto pueda, lo soluciono! 

💃
