### ISSUE TITLE
[BUG] Error al cargar 

### ISSUE THREAD

**Issue by MattLeBlancc** [voidpixel/game#3]
Al iniciar voidpixel con brave (navegador) no "carga" de forma correcta y se esta todo en blanco, Se soluciona si utilizo firefox 
![Sin aaa](https://user-images.githubusercontent.com/51381960/58905934-df5d4380-86d8-11e9-9a66-2891cb1a4dde.jpg)

**Comment by pagoru** [comment]
Esto parece ser un problema más del tipo de render que realiza el navegador con WebGL, creo que no es responsabilidad mia, aunque le daré un vistazo.
