### ISSUE TITLE
[NEW] Reparar la textura de las esquinas para ser constantes con el sombreado del jugador.

### ISSUE THREAD

**Issue by SmashyTomaty** [voidpixel/game#30]
**Describe the solution you'd like**
Se puede modificar la textura, intente rotar el sombreado, pero no queda tambien como una modificacion completa.

**Describe alternatives you've considered**
Obviamente, si la textura queda sin unsar (scrapped), no pasa nada.
El rotado de textura temporal puede funcionar.

**Additional context**
Pongo mi ejemplo en attachment.
![Badoo4](https://user-images.githubusercontent.com/51382099/59171414-7296de80-8b08-11e9-91fb-b41b96926d7f.png)

**Comment by pagoru** [comment]
La textura del jugador está desactualizada con respecto al pixelart de los bloques, así que no. El planteamiento es cambiar al personaje.
