### ISSUE TITLE
[NEW] Autokeys.

### ISSUE THREAD

**Issue by meltstrap** [voidpixel/game#31]
Podría haber un script para autogenerar keys diariamente/semanalmente/mensualmente el cual podría funcionar así:

1. Generar 12 caracteres alfanuméricos aleatorios y almacenarlos en una variable. (Se podría hacer una función y loopearla en variables diferentes para generar más)

2. Enviar una request a la base de datos con las keys para que sean almacenadas.

3. Imprimir las keys en la salida.

También se podría aplicar en un bot de Discord o en una API por Twitter para que las envíe automáticamente. Y si se quiere repetir el proceso periódicamente, se podría aplicar a un cronjob.

**Comment by pagoru** [comment]
No voy a implementar un sistema de keys automáticas.
