### ISSUE TITLE
[BUG] Al entrar al juego y apretar la tecla ENTER el personaje ya no se mueve más

### ISSUE THREAD

**Issue by Harry4321** [voidpixel/game#33]
Descripción:
El juego deja de reconocer el mouse al darle ENTER, por ende el jugador ya no se puede mover 

Para reproducir el error simplemente hay que hacer:
1. Loguearse en el juego
2. Apretar espacio y enter dos veces o más seguidamente
3. El personaje se queda congelado.

**Comment by pagoru** [comment]
En un principio son errores por la implementación del futuro chat, tengo que mirarlo. He conseguido reproducir el error.
