### ISSUE TITLE
[BUG] API Error on code with Ñ

### ISSUE THREAD

**Issue by Beanster199** [voidpixel/game#35]
Well, this is not a code problem at all, it might be a data base table structure problem. But when you insert Ñ on Alpha Code inputs, the server returns Error 500.  

![Screenshot_8](https://user-images.githubusercontent.com/43387209/59315105-ad2a8380-8c8e-11e9-8ad0-3d4cba30c7f8.png)

**Comment by pagoru** [comment]
Working as expected, not a "data base table structure"...
