### ISSUE TITLE
[NEW]Cambiar el zoom de la web deberia escalar las texturas.

### ISSUE THREAD

**Issue by SmashyTomaty** [voidpixel/game#36]
**Is your feature request related to a problem?**
Al aumentar el zoom de la pagina usando la toolbar superior, las texturas de el juego son escaladas automaticamente, pero la estetica de pixeles se vuelve borrosa.

**Describe solutions you've considered**
~~1. Crear unas texturas de mayor resolución y remplazarlas segun la configuración, esto seria ideal, pero podria ser muy lento de implementar.~~
~~2. Se podira procesar el escalamiento separado, si se puede usando interpolacion por el vecino mas cercano al procesar la imagen. Esto podria ser muy lento para algunos ordenadores.~~
~~3. Se podria mantener el juego siempre en la misma resolucion forzando el tamaño de todo en la pagina para ser siempre el mismo sin importar el zoom del navegador. Esta podria ser la mas rapida para implementar.~~

**Additional context**
tambien funciona para tamaños mas pequeños, aunque a partir de el 50% se hace dificil de destinguir que hay en la pantalla.

Y aqui un ejemplo de como se ve, se ve mejor si abres la imagen en pantalla completa:
![Badoo](https://user-images.githubusercontent.com/51382099/59458933-2803b380-8de1-11e9-8ae0-7fbf7217e76a.png)

**Comment by pagoru** [comment]
La resolución de las texturas es la más baja posible, realmente no es necesario eso, solo es necesario detectar cuando se hace una redimensión. 
Toca arreglarlo. 
🤓
