### ISSUE TITLE
[BUG] Problemas con la fuente

### ISSUE THREAD

**Issue by xzebra** [voidpixel/game#38]
**Describe the bug**
Cuando entras al mapa las fuentes no son las que deberían. Pero, si entra un nuevo jugador al mapa, sí que se le pone la fuente correcta.

Duplicados: #39 

**To Reproduce**
1. Entrar al mapa (si hay jugadores conectados verás la fuente incorrecta)
2. Esperar a que entre algún jugador (y se le pondrá la fuente correcta)

**Expected behavior**
Al entrar al mapa debería ponerse la fuente correcta a los jugadores ya conectados.

**Screenshots**
Al entrar al mapa:
![image](https://user-images.githubusercontent.com/20362769/59563594-516c4b80-903c-11e9-86cd-bf9b5608dc52.png)
![image](https://user-images.githubusercontent.com/20362769/59563602-6648df00-903c-11e9-94f4-ab6e34d27024.png)
![imagen](https://user-images.githubusercontent.com/1286535/59564886-6e107f80-904c-11e9-86ec-398269a4d19f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome & Firefox
 - Version: 74

**Comment by pagoru** [comment]
Solucionado para la siguiente versión.
