### ISSUE TITLE
[BUG] Los nombres no se muestran en Firefox

### ISSUE THREAD

**Issue by LuqueDaniel** [voidpixel/game#39]
**Describe the bug**
En Firefox aparece el recuadro del nombre, pero no el texto.

**To Reproduce**
1. Iniciar sesión usando firefox
2. Si hay jugadores, no se verá el texto de sus nombres

**Expected behavior**
Ver el texto del nombre de los jugadores

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1286535/59564886-6e107f80-904c-11e9-86ec-398269a4d19f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 67.0.2

**Additional context**
He probado con Chrome y no ocurre.

**Comment by pagoru** [comment]
Duplicado de #38
