### ISSUE TITLE
[BUG] 404 Not Found al intentar recuperar la clave

### ISSUE THREAD

**Issue by iRyzor** [voidpixel/game#48]
**Describe the bug**
404 Not Found al intentar recuperar la clave

**To Reproduce**
1. Clicar en reset your password
2. Poner el email
3. Ir a la bandeja de entrada
4. Clicar al link que te envian
5. 404 Not Found

**Expected behavior**
Poder cambiar la clave

**Screenshots**
![image](https://user-images.githubusercontent.com/8194839/61096012-f142ac80-a423-11e9-996c-81ec327280cd.png)

**Desktop (please complete the following information):**
Chrome

**Comment by pagoru** [comment]
Ya arreglado para la siguiente versión!
