### ISSUE TITLE
[BUG] Desaparece "cursor" del bloque al cambiar el zoom del navegador

### ISSUE THREAD

**Issue by ComplexRalex** [voidpixel/game#49]
**Describe the bug**
Al momento de cambiar el zoom de la página, el "cursor" (contorno amarillo del bloque) se desfasa respecto al cursor del sistema operativo.

**To Reproduce**
1. Acceder a Voidpixel (in-game)
2. Dar click a cualquier sitio (comprobando que funciona)
3. Cambiar el zoom de la página
4. Intentar dar click en cualquier zona de la pantalla
5. Ver que se muestra el error

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Google Chrome

**Additional information**
Si se regresa al zoom que estaba desde un principio, el bug no se reproduce

**Comment by pagoru** [comment]
Duplicado de https://github.com/voidpixel/game/issues/37
