### ISSUE TITLE
[BUG]Error al iniciar sesion

### ISSUE THREAD

**Issue by WordUsername** [voidpixel/game#54]
**Describe the bug**
Si te desconectas de tu cuenta y volves a iniciar sesion este no te va permitir entrar.

**To Reproduce**
1. Entrar a la pagina
2. Hacer clic en Log Out
3. Volver a iniciar sesion

**Expected behavior**
Deberia poder iniciar sesion normalmente.

**Desktop:**
 - OS: Windows 7
 - Browser: Google Chrome

**Additional context**
Si entras en una pestaña en modo incognito el error no ocurre.

**Comment by pagoru** [comment]
He realizado un cambio en el login, si tenias una sesión antigua, solo tienes que iniciar sesión y cerrar todas las pestañas del navegador, volverlo a abrir y ya estará solucionado el problema.
