### ISSUE TITLE
[BUG] El texto de la interfaz se mueve junto al mundo

### ISSUE THREAD

**Issue by SAIGMan** [voidpixel/game#61]
**Descripción**
El texto que dice "Report a bug" no cambia su posición y se queda atrás.

**Procedimiento**
Como replicar el error:
1. Seleccionar una casilla para moverse
2. posar el puntero sobre el icono de "Report a bug" 

**Pruebas**
![2019-11-17_20-53-32](https://user-images.githubusercontent.com/20034288/69016392-bbd34000-097c-11ea-8fe2-c46f22faa224.gif)

**Datos Tecnicos**
 - Browser: Chrome 78.0.3904.97
 - Versión de voidpixel: 1.13.0

Duplicados: #63

**Comment by pagoru** [comment]
Arreglado para la siguiente update!
