### ISSUE TITLE
[BUG] Personaje bloqueado (no se puede mover) 

### ISSUE THREAD

**Issue by SirMinKo** [voidpixel/game#62]
**Descricpción**

Andando por el spawn de vez en cuando el personaje se bloquea y no puedo moverme de la casilla en la que me encuentro, puedo hacer cualquier otra cosa menos moverme.

**Procedicimiento**

Andar un poco por el spawn simplemente.

**Especificaciones técnicas**

 - Ubuntu 19.10
 - Chrome 78.0.3904.108 (Build oficial) (64 bits)
 - Voidpixel 3.14.0-INDEV

**Comment by Tau5** [comment]
Puedo reproducirlo en EndeavourOS con Firefox 70.0.1 (64 Bits). Al refrescar la página se vuelve a desbloquear

**Comment by pagoru** [comment]
Se produce cuando se hace click en la casilla de debajo del personaje.

**Comment by pagoru** [comment]
Arreglado para la próxima update!
