### ISSUE TITLE
[BUG] El texto de la interfaz se mueve junto al mundo

### ISSUE THREAD

**Issue by aurgiyalgo** [voidpixel/game#63]
**Descripción**
El texto flotante que aparece al colocar el mouse sobre algunos elementos de la interfaz no se mantiene estático en la pantalla mientras se mueve el jugador, y se mueve con el mundo hasta que el puntero cambia de posición.

**Procedimiento**
1. Hacer clic en una casilla para moverse a ella
2. Colocar el mouse sobre un elemento que muestre texto flotante

**Especificaciones**
 - Windows 10
 - Google Chrome (78.0.3904.108 (Build oficial) (64 bits))
 - Voidpixel 3.14.0-INDEV

**Comment by pagoru** [comment]
Duplicado #61
