### ISSUE TITLE
Jugadores que se quedan idle dejan un "fantasma" debajo de ellos.

### ISSUE THREAD

**Issue by SmashyTomaty** [voidpixel/game#7]
No se si ocure todo el rato, pero el fantasma que dejan los jugadores solo se ve sobre el vacio negro de fondo. debajo de la plataforma.
![Badoo](https://user-images.githubusercontent.com/51382099/58906957-bdf95900-86d2-11e9-86af-ec4a97a2552f.png)
![Badoo 2](https://user-images.githubusercontent.com/51382099/58906958-bdf95900-86d2-11e9-973e-78511589fd04.png)
Es posible que tambien se queda una minetras el jugador este en la plataforma, pero no es visible.

Edit: Investigue mas, lo mas probable es que si se encuentra debajo de la plataforma.
Pude probar tambien, el fantasma aparece cuando se mueve el jugador y solo dejan uno a la vez.
![Badoo3](https://user-images.githubusercontent.com/51382099/59151002-9c111680-89f1-11e9-9890-2faad2f1069a.png)

**Comment by pagoru** [comment]
Solucionado #16
